apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgis
  namespace: data-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgis
  template:
    metadata:
      labels:
        app: postgis
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: postgis
          image: aleepl/postgis:17.2
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: postgres-secrets
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgis-storage
              mountPath: /var/lib/postgresql/data  # PostgreSQL default data directory
      restartPolicy: Always
      volumes:
        - name: postgis-storage
          persistentVolumeClaim:
            claimName: postgis-pvc