apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgis-pv
  namespace: data-storage
spec:
  capacity:
    storage: 5Gi # If storage is not enough. it will need to be migrated to increase it
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: "/mnt/data/postgis_v1"
