apiVersion: v1
kind: Service
metadata:
  name: internal-postgis-sv
  namespace: data-storage
spec:
  selector:
    app: postgis
  ports:
    - protocol: TCP
      port: 5432  # External service port
      targetPort: 5432  # Internal container port
  type: ClusterIP  # Use LoadBalancer if exposing externally

---

apiVersion: v1
kind: Service
metadata:
  name: local-postgis-sv
  namespace: data-storage
spec:
  selector:
    app: postgis
  ports:
    - protocol: TCP
      port: 5432  # External service port
      targetPort: 5432  # Internal container port
      nodePort: 30032
  type: NodePort  # Use LoadBalancer if exposing externally
